#
# File: Rexec.msg
# Date: 23-Nov-2016
# By  : Kevin L. Esteb
#
# These are the messages for XAS Rexec modules.
#

[messages]
rexec_server_error = %s, status: %s, message: %s, reason: %s
rexec_action       = %s: performing a "%s" on %s
rexec_started      = %s: starting to do a "%s" on %s
rexec_finished     = %s: finished doing "%s" on %s
rexec_unable       = %s: unable to %s for %s
rexec_nojob        = %s: no current session for %s
rexec_starting     = %s: starting %s
rexec_toomany      = %s: delaying %s, to many jobs already running

